//! Keyword/intent shortcuts for about-app and clearly off-scope questions.
//! These replies are hardcoded — never generated by the LLM.
//!
//! Policy: **conservative**. Only clear About / clear OutOfScope phrases are
//! intercepted. Ambiguous messages fall through to RAG+LLM.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum StaticIntent {
    AboutApp,
    OutOfScope,
}

const ABOUT_REPLY: &str = "Men Faqih AI by MOND — O‘zbekiston qonunchiligi bo‘yicha to‘liq oflayn yuridik yordamchiman. Hozircha Mehnat kodeksi va Fuqarolik kodeksi doirasida ishlayman. Internetga ulanish shart emas.";

const OUT_OF_SCOPE_REPLY: &str = "Faqih AI faqat Mehnat kodeksi va Fuqarolik kodeksi bo‘yicha savollarga javob beradi. Umumiy mavzular yoki internetdan ma’lumot izlash men uchun mavjud emas — bu oflayn model.";

/// Slightly longer copy for Settings → Dastur haqida (kept in sync with chat About reply).
pub const ABOUT_PAGE_TEXT: &str = "Faqih AI by MOND — O‘zbekiston qonunchiligi bo‘yicha desktop yuridik yordamchi. Dastur 100% oflaynda ishlaydi: bulutli AI yo‘q, internet talab qilinmaydi. Hozirgi qamrov: Mehnat kodeksi va Fuqarolik kodeksi. Bu yuridik maslahat o‘rnini bosmaydi — manbalarni tekshiring.";

pub fn static_reply(intent: StaticIntent) -> &'static str {
    match intent {
        StaticIntent::AboutApp => ABOUT_REPLY,
        StaticIntent::OutOfScope => OUT_OF_SCOPE_REPLY,
    }
}

/// Normalize for matching: lowercase, fold common apostrophes, collapse spaces.
fn normalize(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    let mut prev_space = false;
    for ch in input.chars() {
        let c = match ch {
            '‘' | '’' | '`' | '\u{02BB}' | '\u{02BC}' => '\'',
            _ => ch,
        };
        let c = c.to_lowercase().next().unwrap_or(c);
        if c.is_whitespace() {
            if !prev_space && !out.is_empty() {
                out.push(' ');
                prev_space = true;
            }
        } else {
            out.push(c);
            prev_space = false;
        }
    }
    out.trim().to_string()
}

fn contains_any(hay: &str, needles: &[&str]) -> bool {
    needles.iter().any(|n| hay.contains(n))
}

/// Legal / in-scope signals — if present, soft About / OutOfScope must not fire.
fn has_legal_signal(n: &str) -> bool {
    const LEGAL: &[&str] = &[
        "mehnat",
        "fuqarolik",
        "fuqaro",
        "kodeks",
        "shartnoma",
        "ish haqi",
        "ishhaqi",
        "oylik",
        "maosh",
        "ta'til",
        "tatil",
        "bo'shat",
        "boshat",
        "xodim",
        "ishchi",
        "ish beruvchi",
        "ishberuvchi",
        "bandlik",
        "majburiyat",
        "da'vo",
        "davo",
        "sud",
        "modda",
        "qonun",
        "huquq",
        "artikl",
        "kompensats",
        "ish staji",
        "ish vaqti",
        "dam olish",
        "meros",
        "ijara",
        "mulk",
        "vasiyat",
        "nikoh",
        "aliment",
        "jarima",
        "intizom",
        "ishga qabul",
        "ishdan",
        "bekor qilish",
        "ishga kirish",
        "ishga olish",
        "labor code",
        "labour code",
        "civil code",
        "employment",
        "dismissal",
        "vacation",
        "article ",
        "трудов",
        "гражданск",
        "кодекс",
        "стать",
        "зарплат",
        "отпуск",
        "увольн",
        "работник",
        "работодател",
        "договор",
        "компенсац",
        "имуществ",
        "наследств",
    ];
    contains_any(n, LEGAL)
}

/// Strong about-app cues — win even if a legal word appears.
fn is_strong_about(n: &str) -> bool {
    const STRONG: &[&str] = &[
        "faqih ai",
        "faqih nima",
        "faqih haqida",
        "dastur haqida",
        "ilova haqida",
        "bu dastur",
        "bu ilova",
        "who are you",
        "who made you",
        "who built you",
        "what can you do",
        "what is faqih",
        "about faqih",
        "about this app",
        "about the app",
        "mond",
    ];
    contains_any(n, STRONG)
}

/// Soft about cues — only when not a legal question.
fn is_soft_about(n: &str) -> bool {
    const SOFT: &[&str] = &[
        "sen kim",
        "siz kim",
        "sen kimsan",
        "siz kimsiz",
        "o'zing haqida",
        "ozing haqida",
        "o‘zing haqida",
        "o'zing haqingda",
        "nima qila olasan",
        "nima qila olasiz",
        "nima qila oladi",
        "nima qila olasizlar",
        "qanday yordam berasan",
        "qanday yordam berasiz",
        "qanday yordam bera olasan",
        "imkoniyatlaring nima",
        "imkoniyatlaringiz nima",
        "internet kerakmi",
        "oflaynmi",
        "offline misiz",
        "offline misan",
        "kim yaratdi",
        "kim yaratgan",
        "kim ishlab chiq",
        "kim ishlab chiqqan",
        "who made",
        "who built",
    ];
    contains_any(n, SOFT)
}

/// Clear general-knowledge / off-topic cues only.
fn is_out_of_scope(n: &str) -> bool {
    const OUT: &[&str] = &[
        "ob-havo",
        "ob havo",
        "weather",
        "погода",
        "bugungi yangilik",
        "yangiliklar",
        "poytaxti",
        "capital of",
        "who is the president",
        "prezident kim",
        "futbol",
        "football",
        "basketball",
        "sport natija",
        "film tavsiya",
        "kino tavsiya",
        "serial",
        "hazil ayt",
        "joke",
        "she'r yoz",
        "she’r yoz",
        "sher yoz",
        "write a poem",
        "retsept",
        "recipe",
        "ovqat pishir",
        "python kod",
        "javascript",
        "kod yozib ber",
        "write code",
        "2+2",
        "2 + 2",
        "solve this equation",
        "chatgpt",
        "openai",
        "google qidir",
        "internetdan top",
        "browsedan",
    ];
    contains_any(n, OUT)
}

/// Returns a static intent when the message should skip RAG/LLM.
/// Ambiguous messages return `None` so the LLM handles them.
pub fn match_static_intent(message: &str) -> Option<StaticIntent> {
    let n = normalize(message);
    if n.is_empty() {
        return None;
    }

    if is_strong_about(&n) {
        return Some(StaticIntent::AboutApp);
    }

    let legal = has_legal_signal(&n);

    if !legal && is_soft_about(&n) {
        return Some(StaticIntent::AboutApp);
    }

    if !legal && is_out_of_scope(&n) {
        return Some(StaticIntent::OutOfScope);
    }

    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn about_app_phrases() {
        let samples = [
            "Faqih AI nima?",
            "Sen kimsan?",
            "Bu dastur nima qila oladi?",
            "Kim yaratdi?",
            "Dastur haqida",
            "What can you do?",
            "Who are you?",
            "MOND nima?",
            "Nima qila olasan?",
        ];
        for s in samples {
            assert_eq!(
                match_static_intent(s),
                Some(StaticIntent::AboutApp),
                "expected AboutApp for: {s}"
            );
        }
    }

    #[test]
    fn out_of_scope_phrases() {
        let samples = [
            "Bugun ob-havo qanday?",
            "Futbol o‘yini natijasi?",
            "Menga retsept ayt",
            "2+2 necha?",
            "ChatGPT haqida gapir",
        ];
        for s in samples {
            assert_eq!(
                match_static_intent(s),
                Some(StaticIntent::OutOfScope),
                "expected OutOfScope for: {s}"
            );
        }
    }

    #[test]
    fn ambiguous_reaches_llm() {
        let samples = [
            "Menga yordam kerak",
            "Yordam kerak",
            "Salom",
            "Tushuntirib bering",
            "Savolim bor",
            "Bu qanday ishlaydi",
            "Haydab yuborishdi, nima qilaman?",
            "Uy egasi chiqarib yubormoqchi",
            "Pulimni to'lamayapti",
            "Ish bilan bog'liq savolim bor",
            "Hayot nima?",
            "Menga maslahat ber",
        ];
        for s in samples {
            assert_eq!(
                match_static_intent(s),
                None,
                "ambiguous must reach LLM: {s}"
            );
        }
    }

    #[test]
    fn legal_questions_not_intercepted() {
        let samples = [
            "Mehnat shartnomasi qanday tuziladi?",
            "Ishdan bo‘shatilganda kompensatsiya bormi?",
            "Fuqarolik kodeksi bo‘yicha ijara shartnomasi",
            "Xodimning ta’til huquqi qancha?",
            "Mehnat kodeksi 89-modda nima deydi?",
            "Ish haqi kechiktirilsa nima qilish kerak?",
            "Shartnomani kim yaratdi va imzolashi shartmi?",
            "Sudga da’vo qilish muddati qancha?",
            "Трудовой договор как расторгнуть?",
            "Mulk huquqi nima?",
            "Ishga kirish tartibi qanday?",
        ];
        for s in samples {
            assert_eq!(
                match_static_intent(s),
                None,
                "legal question must reach LLM: {s}"
            );
        }
    }

    #[test]
    fn strong_about_wins_with_legal_words() {
        assert_eq!(
            match_static_intent("Faqih AI mehnat kodeksi bo‘yicha ishlaydimi?"),
            Some(StaticIntent::AboutApp)
        );
    }

    #[test]
    fn replies_are_short() {
        for intent in [StaticIntent::AboutApp, StaticIntent::OutOfScope] {
            let text = static_reply(intent);
            let sentences = text.matches('.').count() + text.matches('?').count();
            assert!(
                (2..=4).contains(&sentences) || text.split_whitespace().count() < 80,
                "reply too long for {intent:?}: {text}"
            );
        }
    }
}
